# Generated by Django 4.1.7 on 2023-04-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_feature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='Teacher',
        ),
    ]
