# Generated by Django 4.1.7 on 2023-04-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_teacher_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
    ]
