# Generated by Django 4.1.7 on 2023-04-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
